# Support Vector Machine(SalaryData_Test and Train)

In [81]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn import svm
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split, cross_val_score

In [82]:
testdata = pd.read_csv('SalaryData_Test(1).csv')
traindata = pd.read_csv('SalaryData_Train(1).csv')

In [83]:
testdata

age      workclass      education  educationno        maritalstatus  \
0       25        Private           11th            7        Never-married   
1       38        Private        HS-grad            9   Married-civ-spouse   
2       28      Local-gov     Assoc-acdm           12   Married-civ-spouse   
3       44        Private   Some-college           10   Married-civ-spouse   
4       34        Private           10th            6        Never-married   
...    ...            ...            ...          ...                  ...   
15055   33        Private      Bachelors           13        Never-married   
15056   39        Private      Bachelors           13             Divorced   
15057   38        Private      Bachelors           13   Married-civ-spouse   
15058   44        Private      Bachelors           13             Divorced   
15059   35   Self-emp-inc      Bachelors           13   Married-civ-spouse   

               occupation    relationship                 race      sex  \
0       Machine-op-inspct       Own-child                Black     Male   
1         Farming-fishing         Husband                White     Male   
2         Protective-serv         Husband                White     Male   
3       Machine-op-inspct         Husband                Black     Male   
4           Other-service   Not-in-family                White     Male   
...                   ...             ...                  ...      ...   
15055      Prof-specialty       Own-child                White     Male   
15056      Prof-specialty   Not-in-family                White   Female   
15057      Prof-specialty         Husband                White     Male   
15058        Adm-clerical       Own-child   Asian-Pac-Islander     Male   
15059     Exec-managerial         Husband                White     Male   

       capitalgain  capitalloss  hoursperweek          native  Salary  
0                0            0            40   United-States   <=50K  
1                0            0            50   United-States   <=50K  
2                0            0            40   United-States    >50K  
3             7688            0            40   United-States    >50K  
4                0            0            30   United-States   <=50K  
...            ...          ...           ...             ...     ...  
15055            0            0            40   United-States   <=50K  
15056            0            0            36   United-States   <=50K  
15057            0            0            50   United-States   <=50K  
15058         5455            0            40   United-States   <=50K  
15059            0            0            60   United-States    >50K  

[15060 rows x 14 columns]

In [84]:
traindata 

age          workclass    education  educationno        maritalstatus  \
0       39          State-gov    Bachelors           13        Never-married   
1       50   Self-emp-not-inc    Bachelors           13   Married-civ-spouse   
2       38            Private      HS-grad            9             Divorced   
3       53            Private         11th            7   Married-civ-spouse   
4       28            Private    Bachelors           13   Married-civ-spouse   
...    ...                ...          ...          ...                  ...   
30156   27            Private   Assoc-acdm           12   Married-civ-spouse   
30157   40            Private      HS-grad            9   Married-civ-spouse   
30158   58            Private      HS-grad            9              Widowed   
30159   22            Private      HS-grad            9        Never-married   
30160   52       Self-emp-inc      HS-grad            9   Married-civ-spouse   

               occupation    relationship    race      sex  capitalgain  \
0            Adm-clerical   Not-in-family   White     Male         2174   
1         Exec-managerial         Husband   White     Male            0   
2       Handlers-cleaners   Not-in-family   White     Male            0   
3       Handlers-cleaners         Husband   Black     Male            0   
4          Prof-specialty            Wife   Black   Female            0   
...                   ...             ...     ...      ...          ...   
30156        Tech-support            Wife   White   Female            0   
30157   Machine-op-inspct         Husband   White     Male            0   
30158        Adm-clerical       Unmarried   White   Female            0   
30159        Adm-clerical       Own-child   White     Male            0   
30160     Exec-managerial            Wife   White   Female        15024   

       capitalloss  hoursperweek          native  Salary  
0                0            40   United-States   <=50K  
1                0            13   United-States   <=50K  
2                0            40   United-States   <=50K  
3                0            40   United-States   <=50K  
4                0            40            Cuba   <=50K  
...            ...           ...             ...     ...  
30156            0            38   United-States   <=50K  
30157            0            40   United-States    >50K  
30158            0            40   United-States   <=50K  
30159            0            20   United-States   <=50K  
30160            0            40   United-States    >50K  

[30161 rows x 14 columns]

In [85]:
testdata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15060 entries, 0 to 15059
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   age            15060 non-null  int64 
 1   workclass      15060 non-null  object
 2   education      15060 non-null  object
 3   educationno    15060 non-null  int64 
 4   maritalstatus  15060 non-null  object
 5   occupation     15060 non-null  object
 6   relationship   15060 non-null  object
 7   race           15060 non-null  object
 8   sex            15060 non-null  object
 9   capitalgain    15060 non-null  int64 
 10  capitalloss    15060 non-null  int64 
 11  hoursperweek   15060 non-null  int64 
 12  native         15060 non-null  object
 13  Salary         15060 non-null  object
dtypes: int64(5), object(9)
memory usage: 1.6+ MB


In [86]:
traindata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30161 entries, 0 to 30160
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   age            30161 non-null  int64 
 1   workclass      30161 non-null  object
 2   education      30161 non-null  object
 3   educationno    30161 non-null  int64 
 4   maritalstatus  30161 non-null  object
 5   occupation     30161 non-null  object
 6   relationship   30161 non-null  object
 7   race           30161 non-null  object
 8   sex            30161 non-null  object
 9   capitalgain    30161 non-null  int64 
 10  capitalloss    30161 non-null  int64 
 11  hoursperweek   30161 non-null  int64 
 12  native         30161 non-null  object
 13  Salary         30161 non-null  object
dtypes: int64(5), object(9)
memory usage: 3.2+ MB


In [87]:
testdata.describe()

age   educationno   capitalgain   capitalloss  hoursperweek
count  15060.000000  15060.000000  15060.000000  15060.000000  15060.000000
mean      38.768327     10.112749   1120.301594     89.041899     40.951594
std       13.380676      2.558727   7703.181842    406.283245     12.062831
min       17.000000      1.000000      0.000000      0.000000      1.000000
25%       28.000000      9.000000      0.000000      0.000000     40.000000
50%       37.000000     10.000000      0.000000      0.000000     40.000000
75%       48.000000     13.000000      0.000000      0.000000     45.000000
max       90.000000     16.000000  99999.000000   3770.000000     99.000000

In [88]:
traindata.describe()

age   educationno   capitalgain   capitalloss  hoursperweek
count  30161.000000  30161.000000  30161.000000  30161.000000  30161.000000
mean      38.438115     10.121316   1092.044064     88.302311     40.931269
std       13.134830      2.550037   7406.466611    404.121321     11.980182
min       17.000000      1.000000      0.000000      0.000000      1.000000
25%       28.000000      9.000000      0.000000      0.000000     40.000000
50%       37.000000     10.000000      0.000000      0.000000     40.000000
75%       47.000000     13.000000      0.000000      0.000000     45.000000
max       90.000000     16.000000  99999.000000   4356.000000     99.000000

In [89]:
# Dropping columns which are not required

traindata = traindata.drop(['education', 'native'],axis = 1)
traindata

age          workclass  educationno        maritalstatus  \
0       39          State-gov           13        Never-married   
1       50   Self-emp-not-inc           13   Married-civ-spouse   
2       38            Private            9             Divorced   
3       53            Private            7   Married-civ-spouse   
4       28            Private           13   Married-civ-spouse   
...    ...                ...          ...                  ...   
30156   27            Private           12   Married-civ-spouse   
30157   40            Private            9   Married-civ-spouse   
30158   58            Private            9              Widowed   
30159   22            Private            9        Never-married   
30160   52       Self-emp-inc            9   Married-civ-spouse   

               occupation    relationship    race      sex  capitalgain  \
0            Adm-clerical   Not-in-family   White     Male         2174   
1         Exec-managerial         Husband   White     Male            0   
2       Handlers-cleaners   Not-in-family   White     Male            0   
3       Handlers-cleaners         Husband   Black     Male            0   
4          Prof-specialty            Wife   Black   Female            0   
...                   ...             ...     ...      ...          ...   
30156        Tech-support            Wife   White   Female            0   
30157   Machine-op-inspct         Husband   White     Male            0   
30158        Adm-clerical       Unmarried   White   Female            0   
30159        Adm-clerical       Own-child   White     Male            0   
30160     Exec-managerial            Wife   White   Female        15024   

       capitalloss  hoursperweek  Salary  
0                0            40   <=50K  
1                0            13   <=50K  
2                0            40   <=50K  
3                0            40   <=50K  
4                0            40   <=50K  
...            ...           ...     ...  
30156            0            38   <=50K  
30157            0            40    >50K  
30158            0            40   <=50K  
30159            0            20   <=50K  
30160            0            40    >50K  

[30161 rows x 12 columns]

In [90]:
# Dropping columns which are not required

testdata = testdata.drop(['education', 'native'],axis = 1)
testdata

age      workclass  educationno        maritalstatus  \
0       25        Private            7        Never-married   
1       38        Private            9   Married-civ-spouse   
2       28      Local-gov           12   Married-civ-spouse   
3       44        Private           10   Married-civ-spouse   
4       34        Private            6        Never-married   
...    ...            ...          ...                  ...   
15055   33        Private           13        Never-married   
15056   39        Private           13             Divorced   
15057   38        Private           13   Married-civ-spouse   
15058   44        Private           13             Divorced   
15059   35   Self-emp-inc           13   Married-civ-spouse   

               occupation    relationship                 race      sex  \
0       Machine-op-inspct       Own-child                Black     Male   
1         Farming-fishing         Husband                White     Male   
2         Protective-serv         Husband                White     Male   
3       Machine-op-inspct         Husband                Black     Male   
4           Other-service   Not-in-family                White     Male   
...                   ...             ...                  ...      ...   
15055      Prof-specialty       Own-child                White     Male   
15056      Prof-specialty   Not-in-family                White   Female   
15057      Prof-specialty         Husband                White     Male   
15058        Adm-clerical       Own-child   Asian-Pac-Islander     Male   
15059     Exec-managerial         Husband                White     Male   

       capitalgain  capitalloss  hoursperweek  Salary  
0                0            0            40   <=50K  
1                0            0            50   <=50K  
2                0            0            40    >50K  
3             7688            0            40    >50K  
4                0            0            30   <=50K  
...            ...          ...           ...     ...  
15055            0            0            40   <=50K  
15056            0            0            36   <=50K  
15057            0            0            50   <=50K  
15058         5455            0            40   <=50K  
15059            0            0            60    >50K  

[15060 rows x 12 columns]

## Feature encoding

In [91]:
from sklearn.preprocessing import LabelEncoder
traindata = traindata.apply(LabelEncoder().fit_transform)
traindata

age  workclass  educationno  maritalstatus  occupation  relationship  \
0       22          5           12              4           0             1   
1       33          4           12              2           3             0   
2       21          2            8              0           5             1   
3       36          2            6              2           5             0   
4       11          2           12              2           9             5   
...    ...        ...          ...            ...         ...           ...   
30156   10          2           11              2          12             5   
30157   23          2            8              2           6             0   
30158   41          2            8              6           0             4   
30159    5          2            8              4           0             3   
30160   35          3            8              2           3             5   

       race  sex  capitalgain  capitalloss  hoursperweek  Salary  
0         4    1           24            0            39       0  
1         4    1            0            0            12       0  
2         4    1            0            0            39       0  
3         2    1            0            0            39       0  
4         2    0            0            0            39       0  
...     ...  ...          ...          ...           ...     ...  
30156     4    0            0            0            37       0  
30157     4    1            0            0            39       1  
30158     4    0            0            0            39       0  
30159     4    1            0            0            19       0  
30160     4    0          107            0            39       1  

[30161 rows x 12 columns]

In [92]:
testdata = testdata.apply(LabelEncoder().fit_transform)
testdata

age  workclass  educationno  maritalstatus  occupation  relationship  \
0        8          2            6              4           6             3   
1       21          2            8              2           4             0   
2       11          1           11              2          10             0   
3       27          2            9              2           6             0   
4       17          2            5              4           7             1   
...    ...        ...          ...            ...         ...           ...   
15055   16          2           12              4           9             3   
15056   22          2           12              0           9             1   
15057   21          2           12              2           9             0   
15058   27          2           12              0           0             3   
15059   18          3           12              2           3             0   

       race  sex  capitalgain  capitalloss  hoursperweek  Salary  
0         2    1            0            0            39       0  
1         4    1            0            0            49       0  
2         4    1            0            0            39       1  
3         2    1           87            0            39       1  
4         4    1            0            0            29       0  
...     ...  ...          ...          ...           ...     ...  
15055     4    1            0            0            39       0  
15056     4    0            0            0            35       0  
15057     4    1            0            0            49       0  
15058     1    1           73            0            39       0  
15059     4    1            0            0            59       1  

[15060 rows x 12 columns]

# Support Vector Machine for testdata
### Building model with Grid Search CV for testdata (SalaryData_Test)

In [93]:
# Splitting data into test data and train data   testing data 30% and training data 70%

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(testdata , testdata['Salary'], test_size=0.3, random_state=42)

In [94]:
x_test

age  workclass  educationno  maritalstatus  occupation  relationship  \
11557   18          2           10              2          12             0   
8018    26          3           13              2           3             0   
8161    19          2            9              0           7             4   
13833   36          2            7              2           7             0   
8953     3          2            9              4          11             3   
...    ...        ...          ...            ...         ...           ...   
13355   41          2            8              4           8             1   
3026    15          2           10              2           2             0   
8940    48          2            9              0           7             1   
4102    12          2            8              2           2             0   
14350   23          2            8              2           5             0   

       race  sex  capitalgain  capitalloss  hoursperweek  Salary  
11557     4    1            0            0            39       0  
8018      1    1            0            0            59       1  
8161      4    0            0            0            39       0  
13833     4    1            0            0            39       0  
8953      4    0            0            0            34       0  
...     ...  ...          ...          ...           ...     ...  
13355     4    1            0           29            39       0  
3026      0    1            0            0            41       0  
8940      1    0            0            0            14       0  
4102      4    1            0            0            39       0  
14350     2    1            0            0            39       0  

[4518 rows x 12 columns]

In [95]:
x_train

age  workclass  educationno  maritalstatus  occupation  relationship  \
11297   35          2            8              2           3             0   
7286    15          5            9              4           2             3   
14892   66          2            9              0           9             4   
14994   19          1           12              0           9             4   
12105   56          1           13              2           3             0   
...    ...        ...          ...            ...         ...           ...   
5191    42          1            8              5           0             4   
13418    7          2            9              4           7             4   
5390    26          2            9              0          12             1   
860     40          2           10              4           7             3   
7270    31          2            8              2           2             0   

       race  sex  capitalgain  capitalloss  hoursperweek  Salary  
11297     4    1           72            0            39       1  
7286      4    1            0            0            19       0  
14892     4    0            0            0            19       0  
14994     4    0            0            0            51       0  
12105     4    1            0            0            19       0  
...     ...  ...          ...          ...           ...     ...  
5191      4    0            0            0            34       0  
13418     4    0            0            0            19       0  
5390      4    1            0            0            44       0  
860       4    0            0            0            39       0  
7270      4    1            0            0            39       1  

[10542 rows x 12 columns]

In [96]:
y_test

11557    0
8018     1
8161     0
13833    0
8953     0
        ..
13355    0
3026     0
8940     0
4102     0
14350    0
Name: Salary, Length: 4518, dtype: int32

In [97]:
y_train

11297    1
7286     0
14892    0
14994    0
12105    0
        ..
5191     0
13418    0
5390     0
860      0
7270     1
Name: Salary, Length: 10542, dtype: int32

## 1. RBF

In [98]:
clf = SVC(kernel="rbf") 
clf.fit(x_train , y_train)
y_pred = clf.predict(x_test)
acc = accuracy_score(y_test, y_pred) * 100
print("Accuracy =", acc)
confusion_matrix(y_test, y_pred) 

Accuracy = 97.78663125276671


array([[3359,   27],
       [  73, 1059]], dtype=int64)

# 2. Linear

In [99]:
clf = SVC(kernel= "linear") 
clf.fit(x_train , y_train)
y_pred = clf.predict(x_test)
acc = accuracy_score(y_test, y_pred) * 100
print("Accuracy =", acc)
confusion_matrix(y_test, y_pred)    

Accuracy = 100.0


array([[3386,    0],
       [   0, 1132]], dtype=int64)

## 3. Poly

In [100]:
clf = SVC(kernel= "poly") 
clf.fit(x_train , y_train)
y_pred = clf.predict(x_test)
acc = accuracy_score(y_test, y_pred) * 100
print("Accuracy =", acc)
confusion_matrix(y_test, y_pred) 

Accuracy = 99.22532093846836


array([[3386,    0],
       [  35, 1097]], dtype=int64)

## 4. Sigmoid

In [101]:
clf = SVC(kernel= "sigmoid") 
clf.fit(x_train , y_train)
y_pred = clf.predict(x_test)
acc = accuracy_score(y_test, y_pred) * 100
print("Accuracy =", acc)
confusion_matrix(y_test, y_pred) 

Accuracy = 63.3908809207614


array([[2700,  686],
       [ 968,  164]], dtype=int64)

# As per the above models for testdata Linear model gives 100% accuracy

# Support Vector Machine for traindata
### Building model with Grid Search CV for traindata (SalaryData_Train)

In [102]:
# Splitting data into test data and train data   testing data 30% and training data 70%

from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(traindata , traindata['Salary'], test_size=0.3, random_state=42)

In [103]:
X_train

age  workclass  educationno  maritalstatus  occupation  relationship  \
27112   18          2            8              2           2             0   
13212    6          2            8              2           5             0   
24111   22          2           12              2           3             5   
22501   16          2            8              0           7             4   
3872    10          3            8              5           0             1   
...    ...        ...          ...            ...         ...           ...   
29802   19          2           11              2           3             5   
5390    24          4            9              2           6             0   
860     20          2            8              2           2             0   
15795   39          4            6              2           7             5   
23654   28          2            9              5           2             1   

       race  sex  capitalgain  capitalloss  hoursperweek  Salary  
27112     4    1            0            0            39       1  
13212     4    1            0            0            39       0  
24111     4    0            0            0            59       1  
22501     4    0            0            0            31       0  
3872      4    1            0            0            37       0  
...     ...  ...          ...          ...           ...     ...  
29802     4    0            0            0            36       0  
5390      4    1           49            0            39       1  
860       4    1            0            0            93       1  
15795     4    0            0            0            39       0  
23654     4    1            0            0            40       0  

[21112 rows x 12 columns]

In [104]:
X_test

age  workclass  educationno  maritalstatus  occupation  relationship  \
217     11          2           14              4           9             1   
24912   24          2            8              2           2             0   
17780   36          2            8              2           7             0   
12484   14          2            8              2           2             0   
8890    17          1           12              3           9             1   
...    ...        ...          ...            ...         ...           ...   
20990   15          2            9              2          11             2   
23327   30          4            9              2           2             0   
24639   24          2           12              5           9             1   
7738     7          2            8              4          11             1   
3882     9          5           12              4           9             1   

       race  sex  capitalgain  capitalloss  hoursperweek  Salary  
217       4    1            0            0            54       1  
24912     1    1            0            0            39       0  
17780     4    1            0            0            49       1  
12484     4    1            0            0            44       0  
8890      4    0            0            0            39       0  
...     ...  ...          ...          ...           ...     ...  
20990     1    0            0            0            39       0  
23327     4    1            0            0            39       1  
24639     2    0          117            0            59       1  
7738      4    1            0            0            29       0  
3882      4    1            0            0            39       0  

[9049 rows x 12 columns]

In [105]:
Y_train

27112    1
13212    0
24111    1
22501    0
3872     0
        ..
29802    0
5390     1
860      1
15795    0
23654    0
Name: Salary, Length: 21112, dtype: int32

In [106]:
Y_test

217      1
24912    0
17780    1
12484    0
8890     0
        ..
20990    0
23327    1
24639    1
7738     0
3882     0
Name: Salary, Length: 9049, dtype: int32

## 1. RBF

In [107]:
clf = SVC(kernel="rbf") 
clf.fit(X_train , Y_train)
Y_pred = clf.predict(X_test)
acc = accuracy_score(Y_test, Y_pred) * 100
print("Accuracy =", acc)
confusion_matrix(Y_test, Y_pred) 

Accuracy = 98.60758094817108


array([[6727,   53],
       [  73, 2196]], dtype=int64)

## 2. Linear

In [108]:
clf = SVC(kernel="linear") 
clf.fit(X_train , Y_train)
Y_pred = clf.predict(X_test)
acc = accuracy_score(Y_test, Y_pred) * 100
print("Accuracy =", acc)
confusion_matrix(Y_test, Y_pred) 

Accuracy = 100.0


array([[6780,    0],
       [   0, 2269]], dtype=int64)

## 3. Poly 

In [109]:
clf = SVC(kernel="poly") 
clf.fit(X_train , Y_train)
Y_pred = clf.predict(X_test)
acc = accuracy_score(Y_test, Y_pred) * 100
print("Accuracy =", acc)
confusion_matrix(Y_test, Y_pred) 

Accuracy = 99.55796220576859


array([[6780,    0],
       [  40, 2229]], dtype=int64)

## 4. Sigmoid

In [110]:
clf = SVC(kernel="sigmoid") 
clf.fit(X_train , Y_train)
Y_pred = clf.predict(X_test)
acc = accuracy_score(Y_test, Y_pred) * 100
print("Accuracy =", acc)
confusion_matrix(Y_test, Y_pred) 

Accuracy = 61.26643828047298


array([[5146, 1634],
       [1871,  398]], dtype=int64)

# As per the above models for traindata Linear model gives 100% accuracy